springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: al.codepie.microservices.core.budgetexpense
  pathsToMatch: /**

api:

  common:
    version: 1.0.0
    title: Budget Expense API
    description: Description of the Budget Expense API...
    termsOfService: MY TERMS OF SERVICE
    license: MY LICENSE
    licenseUrl: MY LICENSE URL

    externalDocDesc: MY WIKI PAGE
    externalDocUrl: MY WIKI URL
    contact:
      name: NAME OF CONTACT
      url: URL TO CONTACT
      email: contact@mail.com

  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, invalid format of the request. See response message for more information
    notFound.description: Not found, the specified id does not exist
    unprocessableEntity.description: Unprocessable entity, input parameters caused the processing to fail. See response message for more information

  budget-expense:
    create-budget-expense:
      description: Creates a budget expense
      notes: |
        # Normal response
        The budget expense information posted to the API.

        # Expected error responses
        1. If a budget expense with the same Id as specified in the posted information already exists,
           an **422 - Unprocessable Entity** error with a "duplicate key" error message will be returned

    update-budget-expense:
      description: Updates a budget expense
      notes: |
        # Normal response
        The budget expense information posted to the API.

        # Expected error responses
        1. If a budget expense with the same Id as specified in the posted information already exists,
           an **422 - Unprocessable Entity** error with a "duplicate key" error message will be returned
        1. If no budget expense information is found, a **404 - Not Found** error will be returned

    get-budget-expense:
      description: Returns a budget expense
      notes: |
        # Normal response
        If the requested budget expense id is found the method will return information regarding:
        1. Budget expense information
        1. Service Addresses\n(technical information regarding the addresses of the microservices that created the response)

        # Expected error responses
        1. If no budget expense information is found, a **404 - Not Found** error will be returned        

    delete-budget-expense:
      description: Deletes a budget expense
      notes: |
        # Normal response
        Budget expense with the specified budgetExpenseId will be deleted.
        The implementation of the delete method is idempotent, i.e. it can be called several times with the same response.

        This means that a delete request of a non-existing budget expense will return **200 Ok**.

    get-budget-expense-aggregate:
      description: Returns a budget expense aggregate
      notes: |
        # Normal response
        If the requested budget sub item ids with the date range from and to are found, the method will return information regarding:
        1. List of Budget expenses information

        # Expected error responses
        1. If no budget expenses information is found, a **404 - Not Found** error will be returned  
        

server:
  port: 7001
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: budget-expense-db

logging:
  level:
    root: INFO
    al.codepie: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb




