springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: al.codepie.microservices.core.budgettype
  pathsToMatch: /**

api:

  common:
    version: 1.0.0
    title: Budget Type API
    description: Description of the Budget Type API...
    termsOfService: MY TERMS OF SERVICE
    license: MY LICENSE
    licenseUrl: MY LICENSE URL

    externalDocDesc: MY WIKI PAGE
    externalDocUrl: MY WIKI URL
    contact:
      name: NAME OF CONTACT
      url: URL TO CONTACT
      email: contact@mail.com

  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, invalid format of the request. See response message for more information
    notFound.description: Not found, the specified id does not exist
    unprocessableEntity.description: Unprocessable entity, input parameters caused the processing to fail. See response message for more information

  budget-type:
    create-budget-type:
      description: Creates a budget type
      notes: |
        # Normal response
        The budget type information posted to the API.

        # Expected error responses
        1. If a budget type with the same Id as specified in the posted information already exists,
           an **422 - Unprocessable Entity** error with a "duplicate key" error message will be returned

    update-budget-type:
      description: Updates a budget type
      notes: |
        # Normal response
        The budget type information posted to the API.

        # Expected error responses
        1. If a budget type with the same Id as specified in the posted information already exists,
           an **422 - Unprocessable Entity** error with a "duplicate key" error message will be returned
        1. If no budget type information is found, a **404 - Not Found** error will be returned

    get-budget-type:
      description: Returns a budget type
      notes: |
        # Normal response
        If the requested budget type id is found the method will return information regarding:
        1. Budget type information
        1. Service Addresses\n(technical information regarding the addresses of the microservices that created the response)

        # Expected error responses
        1. If no budget type information is found, a **404 - Not Found** error will be returned        

    delete-budget-type:
      description: Deletes a budget type
      notes: |
        # Normal response
        Budget type with the specified budgetTypeId will be deleted.
        The implementation of the delete method is idempotent, i.e. it can be called several times with the same response.

        This means that a delete request of a non-existing budget type will return **200 Ok**.


server:
  port: 7003
  error:
    include-message: always

# Strongly recommended to set this property to "none" in a production environment!
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost/budget-type-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000

logging:
  level:
    root: INFO
    al.codepie: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql_budget_type/budget-type-db



